### ISSUE TITLE
USB C Plaid

### ISSUE THREAD

**Issue by stephen-huan** [stephen-huan/plaid#1]
Switch from Micro-USB to USB-C by redesigning PCB.
Note: this has already been [done](https://github.com/hsgw/plaid/pull/27), but they put the two resistors to the right of the connector, moving the LEDs. There is a nice, empty, space below the reset button and to the left of the 2x3 header. Putting the 2 5.1 kohm resistors there has also already been [done](https://keycapsss.com/diy-kits/90/plaid-gold-keyboard-kit-usb-c-mx/choc?c=17) but not in an open-source manner (as far as I'm aware).

- Copy [romeo](https://github.com/coseyfannitutti/romeo) (very similar, atmega382pu, usb c)
- Need to add 2 5.1 kohm resistors 
- [PCB design guide](https://wiki.ai03.com/books/pcb-design/page/usb-type-c)

**Comment by piit79** [comment]
Hey, thanks for mentioning my pull request. This was actually my very first attempt at a PCB modification in KiCad, and it shows :) I didn't dare change much, and I still managed to botch the schematics on the first proto :) I'll try to improve the layout of the PCB soon according to your comments.

**Comment by stephen-huan** [comment]
Oh haha, these were just notes to myself if I ever got around to re-designing the PCB. No worries, I don't have any electronics experience so it was helpful to see what others had done. I did not know GitHub linked these...

Sorry for the trouble, I would have worded the message nicer if I knew someone other than myself would have read it :p

**Comment by piit79** [comment]
Hey, don't worry! I didn't take any offence :) As I said, that was my very first foray into KiCad, so I'm sure it's less than optimal to say the least. It was the best I could do back then, but I've practiced quite a bit since, so I should probably revisit :)
